apiVersion: v1
kind: Pod
metadata:
  name: debug-backend
  namespace: aws-simulation
spec:
  containers:
    - name: debug
      image: mariamelkotb/shopsphere-backend:local
      command: ["sleep", "3600"]
      envFrom:
        - secretRef:
            name: shopsphere-backend-secret
