apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: aws-simulation
spec:
  selector:
    app: shopsphere-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
