apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: aws-simulation
  labels:
    app: shopsphere-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-frontend
  template:
    metadata:
      labels:
        app: shopsphere-frontend
    spec:
      containers:
        - name: frontend
          image: mariamelkotb/shopsphere-frontend:local
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://backend-service:5000/api"
