apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gcp-simulation
  labels:
    app: shopsphere-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopsphere-backend
  template:
    metadata:
      labels:
        app: shopsphere-backend
    spec:
      containers:
        - name: backend
          image: mariamelkotb/shopsphere-backend:local
          imagePullPolicy:  Always
          
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: shopsphere-backend-secret
